language: r
cache:
  packages: true
r:
    - release
    - devel 
os:
    - linux
sudo: false
latex: false
warnings_are_errors: true
cran: https://cran.rstudio.com
notifications:
  email:
    on_success: change
    on_failure: change
after_success:
    - Rscript -e 'covr::codecov()'
    - Rscript -e 'lintr::lint_package()'
r_github_packages:
  - piecepackr/piecepackr
  - piecepackr/ppgames
  - jimhester/lintr
  - r-lib/covr
